import React, { Component } from 'react';
import authReducer from '../reducers/authReducer';
import { PromiseProvider } from 'mongoose';
import { connect } from 'react-redux';
import { Link } from 'react-router-dom';
import Payments from './Payments';

class Header extends Component {
  renderContent() {
    switch (this.props.auth) {
      case null:
        return;
      case false:
        return (
          <li>
            <a href="/auth/google">Login with Google</a>
          </li>
        );
      default:
        return [
          <li key="1">
            <Payments />
          </li>,
          <li key="3" style={{ margin: '0 10px' }}>
            Credits: {this.props.auth.credits}
          </li>,
          <li key="2">
            <a href="api/logout">Log out</a>
          </li>
        ];
    }
  }

  render() {
    return (
      <nav>
        <div className="nav-wrapper">
          <Link
            to={this.props.auth ? '/surveys' : '/'}
            className="left brand-logo"
          >
            Emaily
          </Link>
          <ul className="right">
            {this.renderContent()}
          </ul>
        </div>
      </nav>
    );
  }
}

//state as argument
function mapStateToProps({ auth }) {
  return {
    //auth property generated by auth reducer
    //(state.auth defined in combine reducer)
    auth: auth
  };
}

//该component会被某个state影响到，需要access
export default connect(mapStateToProps)(Header);
